services:
    db:
        image: postgres:16-alpine
        platform: 'linux/amd64'
        restart: always
        environment:
            - POSTGRES_DB=${DATABASE_DB}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ./.data/database:/var/lib/postgresql/data
        ports:
            - '${DATABASE_PORT_OUT}:5432'

    app:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
        restart: always
        env_file:
            - ../.env
        environment:
            - PORT=${PORT}
            - FRONTEND_URL=${FRONTEND_URL}
        ports:
            - '${PORT}:${PORT}'
        depends_on:
            - db
