export enum ErrorCodeEnum {
    AUTH_FAIL = 'AUTH_FAIL',
    INVALID_QUERY_STRING = 'INVALID_QUERY_STRING',
    ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
    ENTITY_CREATION_FAIL = 'ENTITY_CREATION_FAIL',
    NOT_ENOUGH_RIGHTS = 'NOT_ENOUGH_RIGHTS',
    NOT_AUTH = 'NOT_AUTH',
    EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
    SLUG_ALREADY_IN_USE = 'SLUG_ALREADY_IN_USE',
}
